# Start with a base image containing Java runtime
FROM openjdk:22-jdk

# Time zone as an environment variable inside the container
ENV TZ=America/New_York

# Running a command was the container starts
RUN ln -fs /usr/share/zoneinfo/$TZ /etc/localtime

# Documents what port should be exposed
EXPOSE 8080

# The application's jar file as a variable in the dockerfile (not the OS)
ARG JAR_FILE=casestudy.jar

# Copying a file from the docker build directory into the container (src -> dst)
ADD ${JAR_FILE} casestudy.jar

# What the container does at the start
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/casestudy.jar"]